save_data: data/
src_vocab: data/vocab.src
tgt_vocab: data/vocab.tgt

overwrite: True

data:
    corpus_1:
        path_src: data/train.en.txt
        path_tgt: data/train.ro.txt
    valid:
        path_src: data/dev.en.txt
        path_tgt: data/dev.ro.txt

batch_size: 4
valid_batch_size: 4

world_size: 1
gpu_ranks: [0]

save_model: models/model
save_checkpoint_steps: 1000
train_steps: 10000
valid_steps: 1000


